### ISSUE TITLE
Your code seems to have a transpile error.

### ISSUE THREAD

**Issue by baoduy** [zicodeng/docz-theme-ztopia#1]
I got an error when using this theme, The code is fine with the default theme.

Oops! Your code seems to have a transpile error. See details below to help you debug

SyntaxError: Unexpected token (1:7) 1 : (<React.Fragment><ErrorMessage> ^

**Comment by zicodeng** [comment]
Hi can you provide a link to your repo or give me a bit more details on this? I can help you debug :)

**Comment by baoduy** [comment]
@zicodeng Sorry for late. Here is my repository 
https://github.com/baoduy/material-detials-forms

**Comment by zicodeng** [comment]
> @zicodeng Sorry for late. Here is my repository
> https://github.com/baoduy/material-detials-forms

Investigating...

**Comment by zicodeng** [comment]
@baoduy Hey, thanks for your patience. Can you try upgrading your `docz-theme-ztopia` to the newest version. I think I fixed the bug. Let me know if you have further issues. Thanks!

btw, it's prob not a good idea to upload your `.docz` folder to GitHub since it is auto generated by Docz, not your source code :)

**Comment by baoduy** [comment]
@zicodeng Thanks for your help. understand the .docz is auto-generated but forgot to update the gitignore. I will try and let you know if any issue.
